### ISSUE TITLE
Scratchpad: list of Chromium forks

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#10]
These may be candidates for TransportSecurity HPKP injection.

* Opera
* https://www.startpage.com/do/search?q=list+of+chromium+forks&rl=to
    - Iridium Browser: https://iridiumbrowser.de/
    - https://wiki.installgentoo.com/index.php/Web_browsers
    - https://en.wikipedia.org/wiki/List_of_web_browsers
    - Slimjet: https://www.techsupportalert.com/content/new-chromium-based-browser-includes-add-ins-standard.htm
    - https://alternativeto.net/software/chromium/?platform=linux
* https://github.com/nylira/prism-break/search?q=browser&type=Issues&utf8=%E2%9C%93
    - ungoogled-chromium: https://github.com/nylira/prism-break/issues/1516
        + Inox patchset: https://github.com/gcarq/inox-patchset
    - Sware Iron: https://github.com/nylira/prism-break/issues/169
        + Epic Privacy Browser: http://epicbrowser.com/
    - Midori: https://github.com/nylira/prism-break/issues/88
    - WhiteHat Aviator: https://github.com/nylira/prism-break/issues/1175
    - Yandex: https://github.com/nylira/prism-break/issues/1207
    - QupZilla: https://github.com/nylira/prism-break/issues/559
    - Comodo Dragon: https://github.com/nylira/prism-break/issues/460

Inclusion on this scratchpad obviously doesn't constitute an endorsement.  (I don't endorse any Chromium-based browsers, FWIW.)

**Comment by periish** [comment]
Are WebKit based browsers considered Chromium based?

Might I also suggest the addition of QtWebEngine browsers as a general category(Falkonne, QuteBrowser) as examples?

**Comment by JeremyRand** [comment]
> Are WebKit based browsers considered Chromium based?
> 
> Might I also suggest the addition of QtWebEngine browsers as a general category(Falkonne, QuteBrowser as examples)?

@periish As far as I'm aware, even Electron is not close enough to Chromium for this purpose, so I'd be really surprised if WebKit browsers and QtWebEngine browsers are.

Also I haven't actually tested HPKP in `TransportSecurity` lately, but I wouldn't be surprised if it no longer is a thing, given that Chromium removed most of the HPKP-related code a while back.  For Windows and GNU/Linux there exist OS-layer API's that we can use instead (`tlsrestrictnss` already does this for GNU/Linux; a similar tool for Windows is under development).  Not really sure about macOS, I haven't looked into how macOS handles this kind of thing.

I'll probably get around to testing this again Soon (TM), and if I confirm that the feature is no longer there, I'll close this issue as WONTFIX.

**Comment by JeremyRand** [comment]
Chromium `TransportSecurity` support was removed in https://github.com/namecoin/ncdns-nsis/pull/54 ; closing as WONTFIX.

@periish If you happen to know of relevant API's in WebKit or QtWebEngine browsers that we could use, please feel free to file a new issue about it.
