### ISSUE TITLE
Remove Layer-1 TLS

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#106]
Currently, the ncdns Windows installer offers to set up both Layer 1 TLS (DANE-EE) and Layer 2 TLS (DANE-TA).  Layer 1 has been deprecated for well over a year because of lousy compatibility (Firefox doesn't support it), lousy scalability (stuffs a self-signature into the blockchain), and lousy attack surface (requires real-time write privs to the root CA list).  At this time, I am about to merge https://github.com/namecoin/ncdns/pull/149 , which will require us to do one of the following:

1. Patch the Windows installer in order to continue supporting Layer 1.
2. Remove Layer 1 from the Windows installer.

The patches needed for (1) are relatively minor right now, but a subsequent ncdns patch that adds support for combining CryptoAPI with Tor will cause major conflicts with a patch for (1).  As such, I am inclined to go with (2).

I just ran `ncdumpzone` today to see who is still using Layer 1.  I can only find 2 `TLSA` records that are using Layer 1:

* `nf.bit` -- The certificate is expired anyway, so removing Layer 1 will not affect service.  This is embarrassing because it's one of ours, but we should be able to get it fixed without any trouble.
* `prism-break.bit` -- The configured IP does not appear to be responding to either HTTP or HTTPS requests, so removing Layer 1 will not affect service.  I can politely ask the PRISM Break maintainers to generate new TLS keys, but it seems like the higher priority for them would be updating the IP address records.

AFAICT everyone else using Namecoin TLS has already upgraded to Layer 2, so    removing Layer 1 should not cause significant disruption.

For reference, generating a Layer 2 certificate can be done via [these instructions](https://www.namecoin.org/docs/name-owners/tls/).  It's pretty easy.

If anyone has objections to this, please let me know.

**Comment by JeremyRand** [comment]
@domob1812 @alpakido Will this removal cause any issues for you?  @alpakido please don't hesitate to ask if you need help fixing the `prism-break.bit` configuration issues.

**Comment by domob1812** [comment]
Nothing I'm aware of

**Comment by JeremyRand** [comment]
Okay, thanks @domob1812 .  I'll wait a week or so for Yana to reply about PRISM Break.

**Comment by JeremyRand** [comment]
Been a week, not going to block on this any longer.  Layer 1 TLS will be removed soon.  My offer to assist PRISM Break in migrating remains open.

**Comment by lukateras** [comment]
Hi @JeremyRand :) I'm very sorry for the late reply – it was the right call not to block this change on `prism-break.bit` as it is currently misconfigured. Right now, `prism-break.org` is served by GitLab Pages, which creates a range of issues, from a lack of .onion or .bit version of the website, to a comparatively weak clearnet visitor privacy due to TLS termination by GitLab.com. I'm going to look into resolving this sometime next month, and I'll reach out to you then!
