### ISSUE TITLE
TransportSecurity isn't present until an HSTS/HPKP site has been visited

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#12]
I just noticed that Chromium's `TransportSecurity` file isn't created when the rest of the profile is created, but instead is only created when the first HSTS or HPKP site is visited.  This means that a stock installation of Chromium that hasn't visited any websites yet will not be detected by ncdns-nsis.

This is not likely to affect many real-world installations, because so many major sites (e.g. Google) use HSTS that I'm guessing almost all real-world Chromium installations have already created the `TransportSecurity` file.  That said, at some point we might want to look into workarounds, e.g. creating the file ourselves if it doesn't exist but its directory does exist.  Not an incredibly high priority IMO.

**Comment by JeremyRand** [comment]
Lower priority now that HPKP is deprecated by Chromium.

**Comment by hlandau** [comment]
Closing this for now.

**Comment by JeremyRand** [comment]
Chromium `TransportSecurity` support was removed in https://github.com/namecoin/ncdns-nsis/pull/54 ; closing as WONTFIX.
