### ISSUE TITLE
Install log should mention if Chromium isn't detected

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#15]
Right now the only Chromium message being logged when Chromium isn't detected is `*** Chromium support was not configured.`, which doesn't actually tell me that Chromium wasn't detected.

The installer should log when Chromium isn't detected.

(h/t to @samurai321 for providing an install log that demonstrated this issue.)

**Comment by hlandau** [comment]
You can detect this case by looking for `Skipping profile because user elected not to configure Chromium`.

**Comment by JeremyRand** [comment]
@hlandau 

> You can detect this case by looking for `Skipping profile because user elected not to configure Chromium`.

Chromium not being detected != Chromium being detected but the user choosing to not configure it.

**Comment by hlandau** [comment]
If `Skipping profile because user elected not to configure Chromium` isn't mentioned, and `Configuring Chromium` isn't mentioned, Chrome wasn't detected.

**Comment by JeremyRand** [comment]
My point is that the installer should affirmatively log something in that case, rather than assuming that the user will recognize that a log message is missing.

**Comment by JeremyRand** [comment]
Chromium `TransportSecurity` support was removed in https://github.com/namecoin/ncdns-nsis/pull/54 ; closing as WONTFIX.
