### ISSUE TITLE
We shouldn't hardcode Chromium profile folder paths

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#3]
Right now, [we hardcode the profile folder paths of Chromium and Chrome](https://github.com/namecoin/ncdns-nsis/blob/cb8b83758772460f7eced3be65a0a22a55ffe56e/ncdns.nsi#L618).

This is a bad idea, because there are other Chromium forks (e.g. Opera) that use their own profile folder, and which we can otherwise support without any trouble.  For example, Opera stores its HPKP list in `AppData\Roaming\Opera Software\Opera Stable\TransportSecurity`.

According to my brief testing, the following PowerShell one-liner will find all Chromium fork HPKP lists for a given user:

~~~
gci C:\Users\user\AppData -recurse -name -force -filter "TransportSecurity" -ErrorAction SilentlyContinue
~~~

It would probably make more sense to use this method rather than hardcoding the paths as we do now.

**Comment by hlandau** [comment]
Uhh! You think "TransportSecurity" is an adequately unambiguous name?

Keying behaviour on whether there exists a "TransportSecurity" directory at any point below the AppData hierarchy seems seriously hazardous. It also has execution time which increases by the size of AppData.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hugo Landau:
> Uhh! You think "TransportSecurity" is an adequately unambiguous
> name?
> 
> Keying behaviour on whether there exists a "TransportSecurity"
> directory at any point below the AppData hierarchy seems seriously
> hazardous. It also has execution time which increases by the size
> of AppData.

Fair point.

Hmm, I don't suppose there's a nice list of Chromium forks anywhere,
so that we can support more than just Chromium and Chrome?


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZNSWGAAoJELPy0WV4bWVwnhIP/3uZZdeESUe7EDZa/OayV0UL
mOkdDFsbJKPDCU2UwBfopPpiRO4aw01SRPuRTFA76Ej9g9x2u1kKNdwfYzn29yX1
gXvqWGYi4yLGRLL7A21tPaGjliOoN4JwrqFw8SrlwbpEks5MuJOxYHZd+gP25go9
4G6JT4zPPCRpDtIVFjoD0hy/+LFKkvy8yAG+nO/pUGLftspUBBu68NDrAzmZm0km
RsUxg1Zx65rlhFf5OC54gqraQUPWuvHN6oPMM7JfHSUPR9eS+AUU2Yoi9SHBtIEr
viavP5eE63fzmIvLTBY9Y50xq68/q5p63ES5xLQhaXbjUqBtyXmpKCzu/yBJ0rQH
GcHTRNdVii++iwkrhZL95qbzQEVgWz16cVaEpCU4O39t633YEzPpJ9Yv7swwhJtV
o1bx+x86iUNT9xdrzQ+iAiCUvCwj1FduLlQ2BLybfEtJdQDx+/Wqpy3xXmcMAlyZ
JVi9610O95ID6rWFkdM+TMs08PV+qI686wcpiKs8DZRx71stvJ8SbtDAAbjVGJ02
7KtPtGToQdOPYd6Rpp4nxVFew9wxi5Baz9kOh4qDoc+vFpOjqmT6zQ1bO6kc9GiQ
Rq5bubOivSHKu9scZPh+zRkzenDnh+P2ek0HTWOaBO3eaee4DYsXHQN50b4XNVzZ
9dc9UAu4E/GZZIjrB7Af
=tHCO
-----END PGP SIGNATURE-----

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

JeremyRand:
> Hmm, I don't suppose there's a nice list of Chromium forks
> anywhere, so that we can support more than just Chromium and
> Chrome?

Now tracking in #10 .

-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZQvzpAAoJELPy0WV4bWVwp0gQAM4EAsByQQPKbWexcVKzxLm+
haUjQqlp7KXeFcMaABlDCDOxp51KKjC7TON7r4DJxdmsERasuMWJEBcomML7ONP6
LTaSWWHbzWWW9Rs0C4XRvwKPAyG2MsL/8bSgK8plkszroRkC94EcTOqf/Ir/oZbM
bQ1JMwAZA/uR/hTb1FM06pX72H8nZg6Cn9AYpLC1YUsJQ1wiAjTNkaplKPur7yzC
vdZTSNtAEBZzsStY9vlR9VW9YFXyd9EbtFE6ZaHZjN4gQumNFCcC1kGiUzDe7yU/
wB/YerU1QjAJ2e6dtpvIMFpOuEF9Sia/MIamTlOdD6QsKO9vlDnUEvzdYDEmY+tT
QbzUJFvcqH0wuydVSnmIKed+DNQ/rN18tihpSOcTtYK3npet6kXBiR2uhiM5YCvO
ByfUAcLZzUSI1gCzUwq4TKCg2/2/lssf+k9J/EUYUO8btmkpJ2z8P2eEge2Rernk
3Wp9miywp0TdA6sb5cE52GMI8zyQPDK52uyn8kslZkdFVI6aAe/VT/+T2GVY2+Lx
6xMTU7UAEtEo5LpV43bOMrMvioWQXf15hST7CmdqRPFNLsT1LKEUZc8BiYIu4A0t
dkmcIpSVbUbd1KI8zCE9noVyAQMzfmx9O904RdE0QDxWiNa7Yo0rt0u1wAHw7lI5
LuRcaj0Y3DmX6IvIDJXr
=Qazo
-----END PGP SIGNATURE-----
