### ISSUE TITLE
Remove regpermrun.ps1 hack

### ISSUE THREAD

**Issue by JeremyRand** [namecoin/ncdns-nsis#8]
The `regpermrun.ps1` hack for accessing both registry views shouldn't be necessary, because the registry key in question is shared between 32-bit and 64-bit registry views.  (I incorrectly assumed earlier in development that they were separate registry keys.)

**Comment by hlandau** [comment]
It doesn't hurt, though, and I trust overkill solutions which overkill in harmless ways to Microsoft not doing something peculiar in the future.

**Comment by JeremyRand** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hugo Landau:
> It doesn't hurt, though, and I trust overkill solutions which
> overkill in harmless ways to Microsoft not doing something peculiar
> in the future.

Fair enough.  I doubt that Microsoft would split that key in the
future, but then again Windows 10 split off the trust stores for Edge,
Windows Store, and Cortana, so who knows what Microsoft will do in the
future.  We can close this issue, I guess.


-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJZNSheAAoJELPy0WV4bWVwcYEP/3jAWXcIZaz/7RiNxof8+FKZ
TCfBmD21TfHdOUdF2gD253hRK5rVjgwFnfpHJLvRL+ll+6vsNmaRzAEXNMszvSy9
qxxexj7jqgRiLmWqDhVkH95w3jQ+pMXMrExGXOKo5VK7rhjqoDh38N5LNxCIPwOd
T2Ydg1hFJdp75JCKFe20iS2LjGhGRq0TwJhRavlu0J1HXi8hp00YtUeboNUruKPm
FvzG+Bcy5lgPrRjuJqVBvqdt3Wv/UumKOT2nC46iYy3n9q1cAL4G6bFce352RMax
ExwCavYCyaU0d8cdHSaCV2Q+vHxGo0fN0iC3vMfKJJW1tZ8PM561I3+yxEWLr9Th
SDD/L4betD2Eikr6ISqKuz4iMOG4Fd8g0T7KmaKo8uIdg5pKs48ScoUFZ2QaZOcY
BsIkqTTOgU8J1FwLt6DYW7dPx5UA3RjlVJOYVKpTxCtMDGdtVE/Ik5GJDJGEu1qb
GQU6sQL7aVR5MjVCGIlg2C2WARlItrK7IzwvboH9yaBgAlS90Bl3CdbQ8oKhX2lf
Td2G1j9FzBVam7jLHacYP5BGQF2iAb8KMxouNA3UDrmDAjBAiB2oXd47b/pYRXuU
0JEwopy0c/09f0h5fJgOkRoptj6UqWet0Ktln464BR/iLCTbZla71mDCEiXZT0HO
MWPAIsfjGRNvfdCsbP7Y
=PKYL
-----END PGP SIGNATURE-----
